package utils

import (
	"crypto/tls"
	"log"
)

// WARNING: DO NOT USE THESE KEYS IN A REAL DEPLOYMENT!

var serverPublicKeys = [...]string{
	`-----BEGIN CERTIFICATE-----
MIICEjCCAbmgAwIBAgIRAJs6juwqbfnuK5O3cihkxp8wCgYIKoZIzj0EAwIwYzEe
MBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMRwwGgYDVQQLDBN5YWJhc3Rh
QHJpb3RtYWNoaW5lMSMwIQYDVQQDDBpta2NlcnQgeWFiYXN0YUByaW90bWFjaGlu
ZTAeFw0yMTAxMTcxMzM4MTJaFw0yMzA0MTcxMjM4MTJaMEcxJzAlBgNVBAoTHm1r
Y2VydCBkZXZlbG9wbWVudCBjZXJ0aWZpY2F0ZTEcMBoGA1UECwwTeWFiYXN0YUBy
aW90bWFjaGluZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAfXFgntWKLr/eyt
Ec8GVVN9L9ogYsGzaafcSewnjdrugi1kkUZEQjyAMvhMEC/NtqFnFzEDHZ9DocBH
wwe4PjijajBoMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAM
BgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFJLGi1XxHWfPp2gtFVtqkn2uffpgMBIG
A1UdEQQLMAmCB3NlcnZlcjAwCgYIKoZIzj0EAwIDRwAwRAIgc9WCOTVaZ/65y7bi
Nrmfb9r2cjjPxNQHlka+K2kSSAkCIGhrfQh6NOBsXLCOVuUUAqfAiP2Clx2EZnXf
03r6s107
-----END CERTIFICATE-----`,

	`-----BEGIN CERTIFICATE-----
MIICETCCAbigAwIBAgIQOk3AtlcYMVQMd0HS0SYTsDAKBggqhkjOPQQDAjBjMR4w
HAYDVQQKExVta2NlcnQgZGV2ZWxvcG1lbnQgQ0ExHDAaBgNVBAsME3lhYmFzdGFA
cmlvdG1hY2hpbmUxIzAhBgNVBAMMGm1rY2VydCB5YWJhc3RhQHJpb3RtYWNoaW5l
MB4XDTIxMDExNzEzMzk0OFoXDTIzMDQxNzEyMzk0OFowRzEnMCUGA1UEChMebWtj
ZXJ0IGRldmVsb3BtZW50IGNlcnRpZmljYXRlMRwwGgYDVQQLDBN5YWJhc3RhQHJp
b3RtYWNoaW5lMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEBnCBB3Jk7wDt7Z6G
RLSJ0nY52qNv7nrnFTt61V9q2iv7cuky28UrdtWcizbaxCpuwt92Crq1HtCDk4bY
l5dV1qNqMGgwDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwG
A1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUksaLVfEdZ8+naC0VW2qSfa59+mAwEgYD
VR0RBAswCYIHc2VydmVyMTAKBggqhkjOPQQDAgNHADBEAiAS/IOgSJQ9AdOrQgPr
/a8YLXKUDhASqboLzjbsLULbVAIgXabswEJLvpBwmiroavdjQeKgqkZ0cmgKdM3R
rmOgyO4=
-----END CERTIFICATE-----`,

	`-----BEGIN CERTIFICATE-----
MIICEzCCAbmgAwIBAgIRANfEdm2uZLzqDwax6ziJg5AwCgYIKoZIzj0EAwIwYzEe
MBwGA1UEChMVbWtjZXJ0IGRldmVsb3BtZW50IENBMRwwGgYDVQQLDBN5YWJhc3Rh
QHJpb3RtYWNoaW5lMSMwIQYDVQQDDBpta2NlcnQgeWFiYXN0YUByaW90bWFjaGlu
ZTAeFw0yMTAxMTcxMzQwMTNaFw0yMzA0MTcxMjQwMTNaMEcxJzAlBgNVBAoTHm1r
Y2VydCBkZXZlbG9wbWVudCBjZXJ0aWZpY2F0ZTEcMBoGA1UECwwTeWFiYXN0YUBy
aW90bWFjaGluZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMNC3FIYnilhV0ph
AndF8ea3RNYOVOa7ZaFo2O6ycyEpSWncrHQjPjxx2/Fey9wQddcfwr5jVCwdukiw
0fuLGNqjajBoMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAM
BgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFJLGi1XxHWfPp2gtFVtqkn2uffpgMBIG
A1UdEQQLMAmCB3NlcnZlcjIwCgYIKoZIzj0EAwIDSAAwRQIhAIDTTzObGBkRpxEt
pJhJKsrTT8wTvDDXzqr77lRvDytaAiAf9XVMkJCLWbMTxdjPhWrtR1Lv94VYRake
v/GtzNdOSw==
-----END CERTIFICATE-----`}

var serverSecretKeys = [...]string{
	`-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgmb8xi8aThFQFgWOG
Ed44Ij6W2iSwIvYx2CB/m2kH7LShRANCAAQH1xYJ7Vii6/3srRHPBlVTfS/aIGLB
s2mn3EnsJ43a7oItZJFGREI8gDL4TBAvzbahZxcxAx2fQ6HAR8MHuD44
-----END PRIVATE KEY-----`,

	`-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg0Lg0AZxkfUsEiTDO
ToQhyyKKOfP23cmFvwtWFXDcoQKhRANCAAQGcIEHcmTvAO3tnoZEtInSdjnao2/u
eucVO3rVX2raK/ty6TLbxSt21ZyLNtrEKm7C33YKurUe0IOThtiXl1XW
-----END PRIVATE KEY-----`,

	`-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgQthS3ujOSu8XHQR0
U1g3RyR/i4Nd/c+4ISF5J6Wlk4mhRANCAATDQtxSGJ4pYVdKYQJ3RfHmt0TWDlTm
u2WhaNjusnMhKUlp3Kx0Iz48cdvxXsvcEHXXH8K+Y1QsHbpIsNH7ixja
-----END PRIVATE KEY-----`}

// ServerCertificates holds the certificates for the servers
var ServerCertificates []tls.Certificate

func init() {
	numServers := 3

	ServerCertificates = make([]tls.Certificate, numServers)

	var err error
	for i := range ServerCertificates {
		ServerCertificates[i], err = tls.X509KeyPair(
			[]byte(serverPublicKeys[i]),
			[]byte(serverSecretKeys[i]))
		if err != nil {
			log.Fatalf("could not load certficate #%v %v", i, err)
		}
	}
}
